name: 'Vault Secret'
description: 'A Github action to get vault secret'
inputs:
  base-url:
    description: 'base-url your vault'
    required: true
    default: null
  token:
    description: 'token of your vault'
    required: true
    default: null
  path:
    description: 'path of your secret'
    required: true
    default: null
  key:
    description: 'key of your secret'
    required: false
    default: null
  
outputs:
  data:
    description: ''
runs:
  using: 'node16'
  main: 'index.js'
