name: 'urVault'
description: 'A Github action to get vault'
inputs:
  baseurl:
    description: 'baseurl your vault'
    required: true
    default: null
  token:
    description: 'api token of your vault'
    required: true
    default: null
  id:
    description: 'vault id'
    required: true
    default: null
  filename:
    description: 'filename'
    required: false
    default: null
  type:
    description: 'type'
    required: false
    default: dotenv
  
runs:
  using: 'node16'
  main: 'index.cjs'
